### PR TITLE
Fix wrong detection of removed settings

### LINKED ISSUE #538: Mapping file _settings.json does not exist for elasticsearch
Getting error while running fscrawler. Below is the stdout output.
```
15:05:02,320 [32mINFO [m [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
15:05:02,322 [32mINFO [m [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
15:05:02,328 [33mWARN [m [f.p.e.c.f.c.ElasticsearchClientManager] failed to create index [crawler], disabling crawler...
15:05:02,328 [1;31mFATAL[m [f.p.e.c.f.FsCrawler] Fatal error received while running the crawler: [Mapping file _settings.json does not exist for elasticsearch version 1 in [/home/user/.fscrawler/_default] dir]
15:05:02,332 [32mINFO [m [f.p.e.c.f.FsCrawlerImpl] FS crawler [crawler] stopped
15:05:02,333 [32mINFO [m [f.p.e.c.f.FsCrawlerImpl] FS crawler [crawler] stopped
```

### PR DESCRIPTION
**Pull request by dadoonet**
Related to https://github.com/dadoonet/fscrawler/issues/538#issuecomment-396540548

We are now testing that `_default/[version]/doc.json` or `_default/[version]/folder.json` exists.

Closes #538

### CODE REVIEW

File: cli/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawler.java [hunk 1]
```diff
@@ -261,13 +258,7 @@ public static void main(String[] args) throws Exception {
                 Path jobMappingDir = configDir.resolve(fsSettings.getName()).resolve("_mappings");
```
Comment (dadoonet) [inline cli/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawler.java]: Code Smell Code Smell: Remove this unused "jobMappingDir" local variable. ([squid:S1481](https://sonarcloud.io/organizations/dadoonet-github/rules#rule_key=squid%3AS1481))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=fr.pilato.elasticsearch.crawler%3Afscrawler-parent&pullRequest=579&issues=AWTql2IgrFWWQMKkjhyG&open=AWTql2IgrFWWQMKkjhyG)

[ISSUE_KEY]: AWTql2IgrFWWQMKkjhyG

File: cli/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawler.java [hunk 2]
```diff
@@ -313,6 +304,23 @@ public static void moveLegacyResources(Path root) {
...
+                    " about upgrades: https://fscrawler.readthedocs.io/en/latest/installation.html#upgrade-fscrawler.",
+                    configDir);
+        } catch (IllegalArgumentException ignored) { }
+        try {
+            // If we are able to read an old configuration file, we should tell the user to check the documentation
+            readDefaultJsonVersionedFile(configDir, Byte.toString(elasticsearchVersion.major), "folder");
+            logger.warn("We found old configuration index settings: [{}/_default/folder.json]. You should look at the documentation" +
+                    " about upgrades: https://fscrawler.readthedocs.io/en/latest/installation.html#upgrade-fscrawler.",
+                    configDir);
+        } catch (IllegalArgumentException ignored) { }
```
Comment (dadoonet) [inline cli/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawler.java]: Code Smell Code Smell: Either remove or fill this block of code. ([squid:S00108](https://sonarcloud.io/organizations/dadoonet-github/rules#rule_key=squid%3AS00108))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=fr.pilato.elasticsearch.crawler%3Afscrawler-parent&pullRequest=579&issues=AWTql2IgrFWWQMKkjhyH&open=AWTql2IgrFWWQMKkjhyH)

[ISSUE_KEY]: AWTql2IgrFWWQMKkjhyH

File: cli/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawler.java (hunk 1 above)
Comment (dadoonet) [inline cli/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawler.java]: Code Smell Code Smell: Remove this useless assignment to local variable "jobMappingDir". ([squid:S1854](https://sonarcloud.io/organizations/dadoonet-github/rules#rule_key=squid%3AS1854))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=fr.pilato.elasticsearch.crawler%3Afscrawler-parent&pullRequest=579&issues=AWTql2IgrFWWQMKkjhyI&open=AWTql2IgrFWWQMKkjhyI)

[ISSUE_KEY]: AWTql2IgrFWWQMKkjhyI
